### ISSUE TITLE
html元素: picture

### ISSUE THREAD

**Issue by geeeger** [geeeger/blog#4]
未来1年之内，可以利用picture元素替代flex + overflow的写法，对图片进行 object-fit操作
```html
<picture>
    <img src="/media/examples/painted-hand-298-332.jpg" />
</picture>
```
```css
img {
  object-fit: cover;
  width: 100%;
  height: 400px;
}
```
